-- Drop existing tables to ensure clean state (Schema Update)
DROP TABLE IF EXISTS public.user_achievements CASCADE;
DROP TABLE IF EXISTS public.achievements CASCADE;

-- Create achievements table
CREATE TABLE public.achievements (
    id bigint generated by default as identity primary key,
    code text not null unique,
    title text not null,
    description text not null,
    category text not null,
    reward_xp integer default 0,
    reward_coins integer default 0,
    icon_name text not null,
    created_at timestamp with time zone default now() not null
);

-- Create user_achievements table to track unlocked achievements
CREATE TABLE public.user_achievements (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    achievement_id bigint references public.achievements(id) on delete cascade not null,
    unlocked_at timestamp with time zone default now() not null,
    unique(user_id, achievement_id)
);

-- Enable RLS
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Everyone can view achievements" 
ON public.achievements FOR SELECT 
USING (true);

CREATE POLICY "Users can view their own unlocked achievements" 
ON public.user_achievements FOR SELECT 
USING (auth.uid() = user_id);

-- Seed Achievements
INSERT INTO public.achievements (code, title, description, category, icon_name, reward_xp, reward_coins) VALUES
('first-steps', 'First Steps', 'Complete your first task.', 'Journey', 'first-steps', 50, 10),
('on-a-roll', 'On a Roll', 'Complete 10 total tasks.', 'Journey', 'on-a-roll', 100, 50),
('task-master', 'Task Master', 'Complete 50 total tasks.', 'Journey', 'task-master', 250, 100),
('productivity-powerhouse', 'Productivity Powerhouse', 'Complete 100 total tasks.', 'Journey', 'productivity-powerhouse', 500, 250),
('grandmaster-of-tasks', 'Grandmaster of Tasks', 'Complete 500 total tasks.', 'Journey', 'grandmaster-of-tasks', 1000, 500),
('pathfinder', 'Pathfinder', 'Complete your first Module (Chapter).', 'Journey', 'pathfinder', 200, 100),
('module-master', 'Module Master', 'Complete 5 Modules.', 'Journey', 'module-master', 500, 250),
('storyteller', 'Storyteller', 'Complete 10 Modules.', 'Journey', 'storyteller', 1000, 500),
('journeys-end', 'Journey''s End', 'Complete an entire Plan (Path).', 'Journey', 'journeys-end', 1000, 1000),
('serial-achiever', 'Serial Achiever', 'Complete 3 Plans (Paths).', 'Journey', 'serial-achiever', 2500, 2500),
('early-bird', 'Early Bird', 'Complete a task before 8 AM.', 'Journey', 'early-bird', 50, 10),
('night-owl', 'Night Owl', 'Complete a task after 10 PM.', 'Journey', 'night-owl', 50, 10),
('weekend-warrior', 'Weekend Warrior', 'Complete 5 tasks on a Saturday or Sunday.', 'Journey', 'weekend-warrior', 100, 50),
('daily-grinder', 'Daily Grinder', 'Complete at least 1 task every day for 5 days.', 'Journey', 'daily-grinder', 200, 100),

('level-up', 'Level Up!', 'Reach Level 2.', 'Character', 'level-up', 50, 10),
('apprentice', 'Apprentice', 'Reach Level 5.', 'Character', 'apprentice', 100, 50),
('journeyman', 'Journeyman', 'Reach Level 10.', 'Character', 'journeyman', 250, 100),
('adept', 'Adept', 'Reach Level 15.', 'Character', 'adept', 500, 250),
('expert', 'Expert', 'Reach Level 20.', 'Character', 'expert', 750, 500),
('master', 'Master', 'Reach Level 25.', 'Character', 'master', 1000, 1000),
('grandmaster', 'Grandmaster', 'Reach Level 30.', 'Character', 'grandmaster', 1500, 1500),
('legend', 'Legend', 'Reach Level 50.', 'Character', 'legend', 2500, 2500),
('mythic', 'Mythic', 'Reach Level 75.', 'Character', 'mythic', 5000, 5000),
('ascended', 'Ascended', 'Reach Level 100.', 'Character', 'ascended', 10000, 10000),

('first-paycheck', 'First Paycheck', 'Earn a total of 100 Coins.', 'Economy', 'first-paycheck', 50, 0),
('piggy-bank', 'Piggy Bank', 'Earn a total of 500 Coins.', 'Economy', 'piggy-bank', 100, 0),
('savings-account', 'Savings Account', 'Hold a balance of 1,000 Coins at once.', 'Economy', 'savings-account', 200, 0),
('treasure-hunter', 'Treasure Hunter', 'Earn a total of 5,000 Coins.', 'Economy', 'treasure-hunter', 500, 0),
('dragons-hoard', 'Dragon''s Hoard', 'Earn a total of 10,000 Coins.', 'Economy', 'dragons-hoard', 1000, 0),
('big-spender', 'Big Spender', 'Purchase your first item from the shop.', 'Economy', 'big-spender', 50, 0),
('shopaholic', 'Shopaholic', 'Spend 2,000 Coins in the shop.', 'Economy', 'shopaholic', 200, 0),
('collector', 'Collector', 'Purchase 5 unique items.', 'Economy', 'collector', 100, 0),
('curator', 'Curator', 'Purchase 15 unique items.', 'Economy', 'curator', 300, 0),
('fashionista', 'Fashionista', 'Purchase 5 items from the "Appearance" (Black/White) category.', 'Economy', 'fashionista', 100, 0),
('decorator', 'Decorator', 'Purchase 5 items from the "Furniture" or "Decor" category.', 'Economy', 'decorator', 100, 0),
('fully-equipped', 'Fully Equipped', 'Own at least 20 items.', 'Economy', 'fully-equipped', 500, 0),
('consumable-connoisseur', 'Consumable Connoisseur', 'Use 5 consumable items.', 'Economy', 'consumable-connoisseur', 100, 0),

('seeker-of-wisdom', 'Seeker of Wisdom', 'Ask the Oracle (AI Chat) for help for the first time.', 'Engagement', 'seeker-of-wisdom', 50, 10),
('oracles-disciple', 'Oracle''s Disciple', 'Ask the Oracle for help 10 times.', 'Engagement', 'oracles-disciple', 200, 50),
('feedback-loop', 'Feedback Loop', 'Send feedback through the app.', 'Engagement', 'feedback-loop', 50, 10),
('determined', 'Determined', 'Log in 3 days in a row.', 'Engagement', 'determined', 100, 50),
('unstoppable', 'Unstoppable', 'Log in 7 days in a row.', 'Engagement', 'unstoppable', 250, 100),
('devoted', 'Devoted', 'Log in 14 days in a row.', 'Engagement', 'devoted', 500, 200),
('marathon-runner', 'Marathon Runner', 'Log in 30 days in a row.', 'Engagement', 'marathon-runner', 1000, 500),
('customizer', 'Customizer', 'Change your character''s appearance/theme for the first time.', 'Engagement', 'customizer', 50, 10),
('plan-abandoner', 'Plan Abandoner', 'Abandon a plan for the first time.', 'Engagement', 'plan-abandoner', 10, 0),
('resilient', 'Resilient', 'Create a new plan after abandoning one.', 'Engagement', 'resilient', 50, 25),
('speed-demon', 'Speed Demon', 'Complete 3 tasks within 1 hour.', 'Engagement', 'speed-demon', 100, 50),
('scholar', 'Scholar', 'Read the generated chapter text for a completed module.', 'Engagement', 'scholar', 50, 10),
('questsmith', 'QuestSmith', 'Unlock 25 other achievements.', 'Engagement', 'questsmith', 1000, 1000)
ON CONFLICT (code) DO NOTHING;

-- Function to check and award achievements
CREATE OR REPLACE FUNCTION public.check_achievements(user_id_input uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    -- Stats variables
    v_completed_tasks integer;
    v_completed_modules integer;
    v_completed_plans integer;
    v_level integer;
    v_xp integer;
    v_total_coins_earned integer; -- Needs tracking or approximation
    v_current_coins integer;
    v_items_purchased integer;
    v_consumables_used integer;
    v_login_streak integer;
    
    -- Achievement IDs and Data
    r_achievement RECORD;
    
BEGIN
    -- 1. GATHER USER STATS
    
    -- Tasks, Modules, Plans (Count from DB)
    SELECT count(*) INTO v_completed_tasks FROM tasks t JOIN quests q ON t.quest_id = q.id JOIN plans p ON q.plan_id = p.id WHERE p.user_id = user_id_input AND t.is_completed = true;
    
    -- Modules (Quests where all tasks are completed)
    SELECT count(*) INTO v_completed_modules 
    FROM quests q 
    JOIN plans p ON q.plan_id = p.id 
    WHERE p.user_id = user_id_input 
    AND (SELECT count(*) FROM tasks t WHERE t.quest_id = q.id) > 0 -- Has tasks
    AND (SELECT count(*) FROM tasks t WHERE t.quest_id = q.id AND t.is_completed = false) = 0; -- No incomplete tasks
    
    -- Plans (Plans where all tasks in all quests are completed)
    SELECT count(*) INTO v_completed_plans 
    FROM plans p
    WHERE p.user_id = user_id_input 
    AND (SELECT count(*) FROM tasks t JOIN quests q ON t.quest_id = q.id WHERE q.plan_id = p.id) > 0 -- Has tasks
    AND (SELECT count(*) FROM tasks t JOIN quests q ON t.quest_id = q.id WHERE q.plan_id = p.id AND t.is_completed = false) = 0; -- No incomplete tasks
    
    -- Profile Stats
    SELECT level, xp, coins INTO v_level, v_xp, v_current_coins FROM profiles WHERE id = user_id_input;
    
    -- Items Purchased (Count user_items + equipped_items? No, user_items contains all ownable items usually. Let's assume user_items)
    SELECT count(*) INTO v_items_purchased FROM user_items WHERE user_id = user_id_input;
    
    -- 2. CHECK SPECIFIC ACHIEVEMENTS (Iterate or specific checks)
    -- Ideally, we'd have a 'rules' engine, but for SQL simplicity, we'll hardcode the checks mapped to codes.
    
    -- Loop through all achievements not yet unlocked by user
    FOR r_achievement IN 
        SELECT * FROM achievements a 
        WHERE NOT EXISTS (SELECT 1 FROM user_achievements ua WHERE ua.achievement_id = a.id AND ua.user_id = user_id_input)
    LOOP
        
        -- CHECK LOGIC BASED ON CODE
        IF r_achievement.code = 'first-steps' AND v_completed_tasks >= 1 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'on-a-roll' AND v_completed_tasks >= 10 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'task-master' AND v_completed_tasks >= 50 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'productivity-powerhouse' AND v_completed_tasks >= 100 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'grandmaster-of-tasks' AND v_completed_tasks >= 500 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
            
        ELSIF r_achievement.code = 'pathfinder' AND v_completed_modules >= 1 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'module-master' AND v_completed_modules >= 5 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'storyteller' AND v_completed_modules >= 10 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
            
        ELSIF r_achievement.code = 'journeys-end' AND v_completed_plans >= 1 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'serial-achiever' AND v_completed_plans >= 3 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);

        -- Level Checks
        ELSIF r_achievement.code = 'level-up' AND v_level >= 2 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'apprentice' AND v_level >= 5 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'journeyman' AND v_level >= 10 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'adept' AND v_level >= 15 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'expert' AND v_level >= 20 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'master' AND v_level >= 25 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'grandmaster' AND v_level >= 30 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'legend' AND v_level >= 50 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'mythic' AND v_level >= 75 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'ascended' AND v_level >= 100 THEN
            PERFORM award_achievement(user_id_input, r_achievement.id);
            
        -- Economy Checks
        -- Note: 'Total Coins Earned' is hard to track without a separate stats table. 
        -- For now, we'll use CURRENT coins for savings, but maybe skip 'earned total' or approx it.
        -- Let's use v_current_coins for 'savings-account'
        ELSIF r_achievement.code = 'savings-account' AND v_current_coins >= 1000 THEN
             PERFORM award_achievement(user_id_input, r_achievement.id);
             
        -- Shop Checks
        ELSIF r_achievement.code = 'big-spender' AND v_items_purchased >= 1 THEN
             PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'collector' AND v_items_purchased >= 5 THEN
             PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'curator' AND v_items_purchased >= 15 THEN
             PERFORM award_achievement(user_id_input, r_achievement.id);
        ELSIF r_achievement.code = 'fully-equipped' AND v_items_purchased >= 20 THEN
             PERFORM award_achievement(user_id_input, r_achievement.id);

        END IF;
    END LOOP;
END;
$$;

-- Helper function to award achievement
CREATE OR REPLACE FUNCTION public.award_achievement(p_user_id uuid, p_achievement_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO public.user_achievements (user_id, achievement_id)
    VALUES (p_user_id, p_achievement_id)
    ON CONFLICT DO NOTHING;
    
    -- Optionally: Add notification logic here or let the client handle it via subscription
END;
$$;
