-- Create the table to store chat message history
CREATE TABLE public.chat_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  role text not null CHECK (role IN ('user', 'assistant')),
  content text not null,
  created_at timestamp with time zone default now() not null
);

-- Enable Row Level Security
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;

-- Create policies to ensure users can only access their own chat history
CREATE POLICY "Users can view their own chat history."
ON public.chat_history FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own chat history."
ON public.chat_history FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own chat history."
ON public.chat_history FOR DELETE
USING (auth.uid() = user_id);
