-- Create the 'tasks' table to hold sub-tasks for each daily quest
CREATE TABLE public.tasks (
    id bigint generated by default as identity primary key,
    quest_id bigint references public.quests(id) on delete cascade not null,
    description text not null,
    reward_coins integer not null default 5,
    is_completed boolean default false not null,
    created_at timestamp with time zone default now() not null
);

-- Add RLS policies to the 'tasks' table
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view tasks for their own quests."
ON public.tasks FOR SELECT
USING (
  auth.uid() IN (
    SELECT p.user_id FROM public.plans p
    JOIN public.quests q ON p.id = q.plan_id
    WHERE q.id = tasks.quest_id
  )
);

CREATE POLICY "Users can update their own tasks."
ON public.tasks FOR UPDATE
USING (
  auth.uid() IN (
    SELECT p.user_id FROM public.plans p
    JOIN public.quests q ON p.id = q.plan_id
    WHERE q.id = tasks.quest_id
  )
);

-- Remove redundant columns from the 'quests' table
ALTER TABLE public.quests
DROP COLUMN IF EXISTS description,
DROP COLUMN IF EXISTS reward_coins;
