-- Create the 'plans' table with the base structure
-- Subsequent migrations will add more columns like 'complexity', 'created_at', etc.
CREATE TABLE public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  goal_text text,
  total_estimated_modules integer,
  total_estimated_duration_weeks integer -- This column is needed since the rename migration was deleted
);

-- Create the 'quests' table with its full structure, including columns that are later removed
-- This is necessary so that later migrations don't fail when trying to drop them
CREATE TABLE public.quests (
    id bigint generated by default as identity primary key,
    plan_id bigint references public.plans(id) on delete cascade not null,
    title text,
    status text default 'pending',
    module_number integer,
    day_number integer,
    created_at timestamp with time zone default now() not null,
    -- These columns are included because a later migration explicitly removes them
    description text,
    reward_coins integer
);
