-- Create the table to store adventure chat message history
CREATE TABLE public.adventure_chat_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  role text not null CHECK (role IN ('user', 'assistant')),
  content text not null,
  created_at timestamp with time zone default now() not null
);

-- Enable Row Level Security
ALTER TABLE public.adventure_chat_history ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Users can view their own adventure chat history."
ON public.adventure_chat_history FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own adventure chat history."
ON public.adventure_chat_history FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own adventure chat history."
ON public.adventure_chat_history FOR DELETE
USING (auth.uid() = user_id);

-- Optional: Migrate existing Adventure DM messages (identified by JSON content) to the new table
-- This moves the Assistant's responses. User messages are harder to distinguish programmatically 
-- without previous context, so they might remain in chat_history.
INSERT INTO public.adventure_chat_history (user_id, role, content, created_at)
SELECT user_id, role, content, created_at
FROM public.chat_history
WHERE content LIKE '{% "message": %}' AND role = 'assistant';

-- Remove the migrated messages from the old table
DELETE FROM public.chat_history
WHERE content LIKE '{% "message": %}' AND role = 'assistant';
