-- Ensure tables exist (in case previous migration failed/rolled back but is marked as done)
CREATE TABLE IF NOT EXISTS public.pet_items (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text,
    cost integer not null DEFAULT 0,
    asset_url text,
    pet_species text[], 
    item_tier integer DEFAULT 1,
    effect_health integer DEFAULT 0,
    effect_happiness integer DEFAULT 0,
    is_full_energy_refill BOOLEAN DEFAULT false NOT NULL,
    created_at timestamp with time zone default now() not null
);

CREATE TABLE IF NOT EXISTS public.user_pet_inventory (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    pet_item_id bigint references public.pet_items(id) on delete cascade not null,
    quantity integer DEFAULT 1, 
    created_at timestamp with time zone default now() not null,
    unique(user_id, pet_item_id)
);

-- Enable RLS (idempotent)
ALTER TABLE public.pet_items ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
    CREATE POLICY "Everyone can read pet items" ON public.pet_items FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.user_pet_inventory ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
    CREATE POLICY "Users can view their own pet inventory" ON public.user_pet_inventory FOR SELECT USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    CREATE POLICY "Users can update their own pet inventory" ON public.user_pet_inventory FOR UPDATE USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Explicitly INSERT data into pet_items
INSERT INTO public.pet_items (name, cost, description, asset_url, item_tier, effect_health, effect_happiness, pet_species) VALUES
-- Universal
('Dirty Water', 5, 'Desperate measures. +5 Health, -5 Happiness.', 'water-bolt.png', 1, 5, -5, NULL),
('Fresh Water', 15, 'Refreshing and clean. +10 Health, +10 Happiness.', 'water-splash.png', 1, 10, 10, NULL),
('Sparkling Spring Water', 50, 'Luxury hydration. +20 Health, +30 Happiness.', 'water-bottle.png', 2, 20, 30, NULL),
('Basic Bed', 100, 'A decent place to sleep. +50 Happiness.', 'bed.png', 2, 0, 50, NULL),
('Luxury Cushion', 500, 'The ultimate comfort. +100 Happiness.', 'pillow.png', 3, 0, 100, NULL),

-- Dog Items
('Dry Kibble', 10, 'Standard dog food. +15 Health.', 'dog-bowl.png', 1, 15, 0, ARRAY['dog']),
('Meaty Bone', 40, 'A tasty treat. +30 Health, +10 Happiness.', 'bone-gnawer.png', 2, 30, 10, ARRAY['dog']),
('Premium Steak', 150, 'Top quality meat. +80 Health, +50 Happiness.', 'steak.png', 3, 80, 50, ARRAY['dog']),
('Old Stick', 0, 'It is sticky. +5 Happiness.', 'wood-stick.png', 1, 0, 5, ARRAY['dog']),
('Tennis Ball', 30, 'Bouncy fun. +20 Happiness.', 'tennis-ball.png', 2, 0, 20, ARRAY['dog']),
('Squeaky Toy', 75, 'Very annoying, very fun. +50 Happiness.', 'plastic-duck.png', 2, 0, 50, ARRAY['dog']),

-- Cat Items
('Fish Scraps', 10, 'Better than nothing. +15 Health.', 'fishbone.png', 1, 15, 0, ARRAY['cat']),
('Tuna Can', 40, 'Delicious tuna. +35 Health.', 'canned-fish.png', 2, 35, 0, ARRAY['cat']),
('Fresh Salmon', 150, 'Fresh from the stream. +80 Health, +60 Happiness.', 'salmon.png', 3, 80, 60, ARRAY['cat']),
('Ball of Yarn', 25, 'Classic entertainment. +25 Happiness.', 'yarn.png', 2, 0, 25, ARRAY['cat']),
('Catnip Mouse', 80, 'They go crazy for it. +60 Happiness.', 'mouse.png', 2, 0, 60, ARRAY['cat']),

-- Chicken Items
('Dried Corn', 5, 'Basic feed. +10 Health.', 'corn.png', 1, 10, 0, ARRAY['chicken', 'chick']),
('Grain Mix', 25, 'A healthy mix. +25 Health.', 'wheat.png', 2, 25, 0, ARRAY['chicken', 'chick']),
('Organic Seeds', 100, 'Premium seeds. +70 Health, +30 Happiness.', 'plant-seed.png', 3, 70, 30, ARRAY['chicken', 'chick']),
('Shiny Pebble', 20, 'Ooh, shiny! +15 Happiness.', 'minerals.png', 1, 0, 15, ARRAY['chicken', 'chick']),

-- Horse Items
('Dry Hay', 15, 'Standard fodder. +20 Health.', 'round-straw-bale.png', 1, 20, 0, ARRAY['horse']),
('Fresh Oats', 50, 'Energy boosting. +40 Health.', 'oat.png', 2, 40, 0, ARRAY['horse']),
('Sweet Apple', 120, 'A sweet treat. +60 Health, +40 Happiness.', 'shiny-apple.png', 3, 60, 40, ARRAY['horse']),
('Salt Lick', 60, 'Essential minerals. +30 Happiness.', 'crystal-cluster.png', 2, 0, 30, ARRAY['horse']),

-- Pig Items
('Slop Bucket', 10, 'It is food. +20 Health.', 'full-wood-bucket.png', 1, 20, 0, ARRAY['pig']),
('Fresh Carrots', 40, 'Crunchy and sweet. +40 Health.', 'carrot.png', 2, 40, 0, ARRAY['pig']),
('Giant Pumpkin', 130, 'A massive feast. +90 Health.', 'pumpkin.png', 3, 90, 0, ARRAY['pig']),
('Mud Bucket', 5, 'For wallowing. +50 Happiness.', 'full-metal-bucket.png', 1, 0, 50, ARRAY['pig']),

-- Raccoon Items
('Trash Bag', 5, 'One man''s trash... +15 Health.', 'trash-can.png', 1, 15, 0, ARRAY['raccoon']),
('Pizza Slice', 45, 'The jackpot. +40 Health, +20 Happiness.', 'pizza-slice.png', 2, 40, 20, ARRAY['raccoon']),
('Shiny Foil', 20, 'So reflective. +20 Happiness.', 'metal-disc.png', 1, 0, 20, ARRAY['raccoon']),
('Gold Watch', 200, 'The ultimate shiny. +100 Happiness.', 'pocket-watch.png', 3, 0, 100, ARRAY['raccoon']),

-- Sheep Items
('Dry Grass', 10, 'Basic grazing. +15 Health.', 'grass.png', 1, 15, 0, ARRAY['sheep']),
('Clover Patch', 40, 'Lucky finding. +35 Health.', 'clover.png', 2, 35, 0, ARRAY['sheep']),
('Alfalfa Hay', 110, 'High quality feed. +75 Health.', 'grain-bundle.png', 3, 75, 0, ARRAY['sheep']),
('Grooming Brush', 50, 'Keeps wool soft. +40 Happiness.', 'comb.png', 2, 0, 40, ARRAY['sheep']),

-- Wolf Items
('Raw Scraps', 15, 'Leftovers. +20 Health.', 'meat.png', 1, 20, 0, ARRAY['wolf']),
('Rabbit Leg', 60, 'Fresh catch. +50 Health.', 'ham-shank.png', 2, 50, 0, ARRAY['wolf']),
('Prime Rib', 180, 'The alpha''s cut. +100 Health.', 'steak.png', 3, 100, 0, ARRAY['wolf']),
('Chew Log', 25, 'Good for teeth. +20 Happiness.', 'log.png', 1, 0, 20, ARRAY['wolf'])

ON CONFLICT (name) DO UPDATE SET
    cost = EXCLUDED.cost, description = EXCLUDED.description, asset_url = EXCLUDED.asset_url,
    item_tier = EXCLUDED.item_tier, effect_health = EXCLUDED.effect_health, effect_happiness = EXCLUDED.effect_happiness, pet_species = EXCLUDED.pet_species;


-- Ensure functions exist and are correct (DROP to handle signature changes if needed)
DROP FUNCTION IF EXISTS public.purchase_pet_item(bigint);

CREATE OR REPLACE FUNCTION public.purchase_pet_item(p_pet_item_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user_id uuid := auth.uid();
    v_cost int;
    v_user_coins int;
BEGIN
    -- Get cost
    SELECT cost INTO v_cost FROM public.pet_items WHERE id = p_pet_item_id;
    IF v_cost IS NULL THEN
        RAISE EXCEPTION 'Item not found.';
    END IF;

    -- Check coins
    SELECT coins INTO v_user_coins FROM public.profiles WHERE id = v_user_id;
    IF v_user_coins < v_cost THEN
        RAISE EXCEPTION 'Not enough coins.';
    END IF;

    -- Deduct coins
    UPDATE public.profiles SET coins = coins - v_cost WHERE id = v_user_id;

    -- Add to inventory (upsert for quantity)
    INSERT INTO public.user_pet_inventory (user_id, pet_item_id, quantity)
    VALUES (v_user_id, p_pet_item_id, 1)
    ON CONFLICT (user_id, pet_item_id) 
    DO UPDATE SET quantity = user_pet_inventory.quantity + 1;
END;
$$;

DROP FUNCTION IF EXISTS public.use_pet_item(bigint);

CREATE OR REPLACE FUNCTION public.use_pet_item(p_pet_item_id bigint)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user_id uuid := auth.uid();
    v_item_name text;
    v_effect_health int;
    v_effect_happiness int;
    v_pet_species text[];
    v_pet_id uuid;
    v_pet_def_id text;
    v_current_quantity int;
BEGIN
    -- Get item details and verify ownership
    SELECT 
        pi.name, 
        pi.effect_health, 
        pi.effect_happiness, 
        pi.pet_species,
        upi.quantity
    INTO 
        v_item_name, 
        v_effect_health, 
        v_effect_happiness, 
        v_pet_species,
        v_current_quantity
    FROM user_pet_inventory upi
    JOIN pet_items pi ON upi.pet_item_id = pi.id
    WHERE upi.pet_item_id = p_pet_item_id AND upi.user_id = v_user_id;

    IF v_item_name IS NULL OR v_current_quantity < 1 THEN
        RAISE EXCEPTION 'Item not found in inventory.';
    END IF;

    -- Check active pet
    SELECT id, pet_def_id 
    INTO v_pet_id, v_pet_def_id
    FROM user_pets 
    WHERE user_id = v_user_id AND status = 'alive' 
    LIMIT 1;
    
    IF v_pet_id IS NULL THEN
        RAISE EXCEPTION 'You have no active companion.';
    END IF;

    -- Species Check
    IF v_pet_species IS NOT NULL AND NOT (v_pet_def_id = ANY(v_pet_species)) THEN
        RAISE EXCEPTION 'This item cannot be used on this type of companion.';
    END IF;

    -- Apply Effects
    UPDATE user_pets 
    SET 
        health = LEAST(100, GREATEST(0, health + v_effect_health)), 
        happiness = LEAST(100, GREATEST(0, happiness + v_effect_happiness)) 
    WHERE id = v_pet_id;

    -- Consume 1 from quantity
    IF v_current_quantity > 1 THEN
        UPDATE user_pet_inventory SET quantity = quantity - 1 WHERE pet_item_id = p_pet_item_id AND user_id = v_user_id;
    ELSE
        DELETE FROM user_pet_inventory WHERE pet_item_id = p_pet_item_id AND user_id = v_user_id;
    END IF;

    RETURN 'Used ' || v_item_name;
END;
$$;
