-- Create the shop_items table
CREATE TABLE public.shop_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  cost integer not null,
  asset_url text,
  slot text not null,
  created_at timestamp with time zone default now() not null
);
ALTER TABLE public.shop_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Shop items are viewable by everyone." ON public.shop_items FOR SELECT USING (true);


-- Create the user_items (inventory) table
CREATE TABLE public.user_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  item_id bigint references public.shop_items(id) on delete cascade not null,
  created_at timestamp with time zone default now() not null,
  unique (user_id, item_id)
);
ALTER TABLE public.user_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own inventory." ON public.user_items FOR SELECT USING (auth.uid() = user_id);


-- Create the equipped_items table
CREATE TABLE public.equipped_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  item_id bigint references public.shop_items(id) on delete cascade not null,
  slot text not null,
  equipped_at timestamp with time zone default now() not null,
  unique (user_id, slot)
);
ALTER TABLE public.equipped_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own equipped items." ON public.equipped_items FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own equipped items." ON public.equipped_items FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own equipped items." ON public.equipped_items FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own equipped items." ON public.equipped_items FOR DELETE USING (auth.uid() = user_id);


-- Seed some basic items into the shop
INSERT INTO public.shop_items (name, description, cost, asset_url, slot) VALUES
('Adventurer''s Tunic', 'A simple, sturdy tunic for a budding adventurer.', 10, '/assets/character/torso_1.svg', 'torso'),
('Steel Helmet', 'A basic steel helmet for protection.', 20, '/assets/character/head_1.svg', 'head'),
('Wooden Sword', 'A trusty wooden sword to start your journey.', 15, '/assets/character/weapon_1.svg', 'weapon');
