-- Create notifications table
CREATE TABLE public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    title text not null,
    message text not null,
    type text default 'info' not null, -- 'info', 'success', 'warning', 'error', 'reward'
    action_link text, -- Optional URL to redirect to
    is_read boolean default false not null,
    created_at timestamp with time zone default now() not null
);

-- RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own notifications."
ON public.notifications FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can update (mark read) their own notifications."
ON public.notifications FOR UPDATE
USING (auth.uid() = user_id);

-- Indexes for performance
CREATE INDEX notifications_user_id_idx ON public.notifications(user_id);
CREATE INDEX notifications_unread_idx ON public.notifications(user_id) WHERE is_read = false;
