-- Create the user_stats table
CREATE TABLE public.user_stats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  plan_id bigint references public.plans(id) on delete cascade not null,
  name text not null,
  value integer default 10 not null,
  created_at timestamp with time zone default now() not null
);

-- Set up Row Level Security
ALTER TABLE public.user_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own stats."
ON public.user_stats FOR SELECT
USING (auth.uid() = user_id);
